commands:
  daily: True
  beg: True
  crime: True
  fish: True
  guess: True
  hunt: True
  dig: True
  search: True
  highlow: True
  postmeme: True
  trivia: True

custom commands:
  enabled: False
  pls dep max:
    enabled: False
    cooldown: 60
    patron cooldown: 60

shifts:
  enabled: False
  active: 7200
  passive: 3600
  
lottery:
  enabled: False
  cooldown: 3600

stream:
  enabled: True
  ads: True
  chat: True
  donations: True

auto buy:
  enabled: True
  laptop: True
  shovel: True
  fishing pole: True
  hunting rifle: True
  keyboard: True
  mouse: True

auto trade:
  enabled: False
  trader token: None
  bank note: True
  tidepod: True

typing indicator:
  enabled: False
  minimum: 0
  maximum: 1
  
cooldowns:
  patron: False
  timeout: 5

logging:
  debug: True
  warning: True